### ISSUE TITLE
question about input_builder 

### ISSUE THREAD

**Issue by colleeneb** [Cavenfish/autogamess#10]
This is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/1612).

I'm trying to test input_builder using the examples of the CSV files that are discussed in the README. 

I set up input.csv to contain data based on the README:
```
$ cat input.csv
Species,Theory,Basis Sets,External Basis Sets,Run Types
H2O,B3LYP,CCD,may-cc-pVDZ,Optimization
``` 

and then I tried to call input_builder using it, and get an error saying that `Basis set may-cc-pv(d+d)z does not exist`. Should I use something other than `may-cc-pVDZ` in the CSV? (I copied it from the README initially.)

```
$ python
>>> import autogamess as ag
>>> csvfile = './input.csv'
>>> savedir= './'
>>> ag.input_builder(csvfile, savedir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/colleen/autogamess/autogamess/input_builder.py", line 170, in input_builder
    fmt='gamess_us', header=False).split('\n')[1:]
  File "/Users/colleen/.local/lib/python3.6/site-packages/basis_set_exchange/api.py", line 168, in get_basis
    bs_data = _get_basis_metadata(name, data_dir)
  File "/Users/colleen/.local/lib/python3.6/site-packages/basis_set_exchange/api.py", line 53, in _get_basis_metadata
    raise KeyError("Basis set {} does not exist".format(name))
KeyError: 'Basis set may-cc-pv(d+d)z does not exist' 
```

Am I doing something wrong? Thanks for any help!

**Comment by colleeneb** [comment]
I'll add a second issue I ran into:

I can get the input file to be generated if I remove the external basis set, so that input.csv is:
```
bash-3.2$ cat input.csv
Species,Theory,Basis Sets,External Basis Sets,Run Types
H2O,B3LYP,CCD,,Optimization
```
However, when I try to use the `new_project` function with `make_inputs=True`, there is an error, since it looks like `new_project.py` has a hard-coded path to `inputs/`:
```
$ python
>>> import autogamess as ag
>>> csvfile = './input.csv'
>>> maindir= './'
>>> title   = 'Project Title/'
>>> ag.new_project(maindir, csvfile, title=title,make_inputs=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/colleen/autogamess/autogamess/new_project.py", line 166, in new_project
    proj_title = title.replace('/', '\n'))
  File "/Users/colleen/autogamess/autogamess/input_builder.py", line 97, in input_builder
    f = open(save_dir + filename, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './inputs/AGv1-0-35_H2O_B3LYP_CCD_opt.inp'
>>> 

```

**Comment by colleeneb** [comment]
Third issue I ran into:

In "Function Documentations", under the "Examples" section in "sort_log", the example code doesn't seem to work. 
For reference, the example code is:

```
Examples
----------
>>>import sort_logs
>>>projdir = './Example/'
>>>sort_logs(projdir)
>>>
```
Based on the function declaration, it needs two inputs, and `import sort_logs` doesn't seem to work.

**Comment by Cavenfish** [comment]
Hey @colleeneb, first off thank you for the comments. In terms of the errors you have posted:

1) It seems EMSL no longer carries the 'may-cc-pv(d+d)z' basis set, which is why the error came up. They still have the other double zeta calendar basis sets though, so if you did instead 'jun-cc-pv(d+d)z' it should work. I will change the README so that it is not there anymore. 

2) This is a bug, I must have forgotten to modify the `savedir` variable. I will fix this right away. Thank you again for catching this.

3) It seems as though when i modified this doc string i forgot to modify the example section. This is an old example that, as you noticed, won't work for the current AutoGAMESS version. I will fix this right away.
