### ISSUE TITLE
Jupyter Notebook example

### ISSUE THREAD

**Issue by shivupa** [Cavenfish/autogamess#12]
Thanks to the helpful discussions between @Cavenfish and @colleeneb, I put together an example notebook (certain parts work only on *nix systems due to the bash ipython magic to run gamess from the notebook but the corresponding commands can be run outside of the notebook on Windows). 

All the files relevant to this are available [here](https://mega.nz/#F!4wIgjICa!BtwC4X8mP7SbI2qEGk0E8A). If mega is blocked on your domain let me know and I can provide the relevant files. I created a pdf in that folder of the notebook for easy viewing. This jupyter notebook may be useful to include in the examples directory at your discretion.

I think I am able to verify the functionality as seen by the file `Water/Spreadsheets/H2O.xlsx`.

I have one future suggestion that I don't feel is required for acceptance. I would like to see the documentation auto generated and hosted online, for example using sphinx and  https://readthedocs.org/. 

Nice job!

**Comment by Cavenfish** [comment]
Hey @shivupa  thank you so much for the jupyter notebook! I will most certainly be adding it to the examples directory as I feel it will certainly help others. Others have also suggested sphinx to me, as soon as I learn how to use ill be sure to document AutoGAMESS with it. 

Thank you for all the comments, they were greatly appreciated!

**Comment by Andrew-S-Rosen** [comment]
Just want to second that I think Sphinx would be an excellent idea going forward! Also not required for acceptance but just chiming in to say it'll be a worthwhile learning experience!
