### ISSUE TITLE
Graceful handling of existing folders

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Cavenfish/autogamess#13]
This is part of the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1612). `ag.new_project(...)` crashes when the directory is already present. I see a few ways this could be improved. Either you could create a new directory (e.g. append a number to the end of the user-provided name, like 'Water_01') or have the code print a warning to the user and gracefully close (instead of crashing with a FileExistsError). You can test this error out for yourself by running Step 5 of the Jupyter Notebook with the files and such already there.

**Comment by Cavenfish** [comment]
@arosen93  That's a great suggestion, ill add that in right away!
