### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by EpithetonOrnans** [Cavenfish/autogamess#23]
Hi :) 
I downloaded the package (and all other packages it requires) and ran pytest from within the tests directory. The result is as follows: 
3 failed, 11 passed

FAILED test_package.py::test_new_project - KeyError: 'Composite Methods'
FAILED test_package.py::test_input_builder - KeyError: 'Composite Methods'
FAILED test_package.py::test_get_data - AssertionError: assert {'2H-H-O Bond...1984284', ...} == {'2H-H-O Bond...5579...

Do you have any idea what went wrong?
Thanks in advance

**Comment by EpithetonOrnans** [comment]
Ok, the first one was simple enough,  the header  'Composite Methods' was missing in the input.csv. Although adding it is simple enough, I do not think that leaving the column blank is a sensible option.
Also, this is by far not the only issue this seems to have...

**Comment by Cavenfish** [comment]
@EpithetonOrnans Thank you for bringing this up to my attention. Yes there are a lot of bug I have not had the chance to solve. I'm happy to see people submitting issues though as these help me identify and fix them. In terms of the error, it is an error in the testing of the module. I will fix that! In terms of it being sensible to leave this column blank I am not sure i understand, also could you point out further issues this would help me greatly.

**Comment by Cavenfish** [comment]
@EpithetonOrnans  Seems like I forgot to update the module tests, both in terms of the csv update and the update in the default unit for bond angles now being degrees instead of radians. I fixed it now.

**Comment by EpithetonOrnans** [comment]
Hi !
Thank you for fixing the issues, the test example works fine! 
I wondered though -and this may be a very stupid question- how to add a new species to the dictionary, as I am trying to calculate the Raman intensities for a certain crystal. Right now, I am just replacing the coordinates in the .inp file, but I think adding it to a species library might be of interest fot other people
Thank you :)

**Comment by Cavenfish** [comment]
@EpithetonOrnans If you send me the coordinates you are putting in the .inp file yourself i can put it into the molecule dictionary for you and your colleges. 

Or, if my explanation is sufficient you should be able to do it yourself. The dictionary works as follows: the `key` is the name of the molecule (or crystal in this case) then the `value` is a list where each item in the list is a string representing the line that would be put in the .inp file after the project name line (don't forget to include new line char `\n` ) but excluding the final $END line.

As an example if your .inp has the following in between the project name line and $END line
```
TD

 C           6.0   0.00000     0.00000     0.00000
 H           1.0   0.63367     0.63367     0.63367
```

The dictionary item should look like this 
```
'CH4':['TD\n','\n',
' C     6.0     0.00000     0.00000     0.00000\n',
' H     1.0     0.63367     0.63367     0.63367\n']
```

Hopefully that helps!
