### ISSUE TITLE
Misc things

### ISSUE THREAD

**Issue by shivupa** [Cavenfish/autogamess#6]
# Formatting
Could the code be autoformatted? E.g. use [autopep8](https://pypi.org/project/autopep8/) `autopep8 -i file.py`

# Typos

README.md:
`inital` -> `initial`
`coordianate` -> `coordinate`
`labled` -> `labeled`
`fucntion` -> `function`
`initlly` -> `initially`

# Docstrings
Files missing docstrings:
`config.py`
`data_finder.py`
`get_data.py`

**Comment by Cavenfish** [comment]
I will look into auto-formatting but I am concerned it may cause bugs in the code.
