### ISSUE TITLE
Paper edits

### ISSUE THREAD

**Issue by shivupa** [Cavenfish/autogamess#7]
I had some comments regarding the paper. Some of these are opinions and stylistic so feel free to disagree. 

- `GAMESS(us)` -> `GAMESS(US)`
- `...have not been experimentally characterized or quantized` -> `...have not been experimentally characterized or quantified`
- `Research utilizing these types of *ab initio* calculations typically require calculations with multiple steps required to achieve each final result.` I  generally agree with this, but perhaps to emphasize the point to someone outside of the field it would be necessary to explain that each step takes a lot of time. For example adding the sentence "This leads to complicated and tedious workflows slowing a user's research.`
- `One of the many popular uses of GAMESS(us) is by chemists, physicists, astro-chemists and astro-physicists
[citationl] for predicting properties of
volatile and unstable species that have not been experimentally characterized or quantized before.` -> `One of the many popular uses of GAMESS(us) is the prediction of properties of
volatile and unstable species that have not been experimentally characterized or quantized before by chemists, physicists, astro-chemists and astro-physicists
[citationsl] .` This flows a bit better IMO.
- I might be biased as I do quantum Monte Carlo calculations, but [Nexus](https://www.sciencedirect.com/science/article/pii/S0010465515002982?via%3Dihub) is super helpful for my workflows, and I feel it is worth mentioning.
- It would be worth mentioning that automation is essential to generate large databases of Raman data. This would have further application for machine learning of Raman data.
- `AutoGAMESS was developed to be versatile in its usability; however the most
effective method to use AutoGAMESS is the integration of short Python scripts
within shell scripts. Several of example scripts can be found in the software's GitHub repository, https://github.com/Cavenfish/autogamess.` This is unclear. Could the examples in the README be added to an examples folder in the repo as well? Also the shell script part may need some explanation as the repo doesn't have an example of shell scripts, they are all python scripts.

Thanks this is an interesting project!

**Comment by shivupa** [comment]
@Cavenfish I wanted to indicate that the "quantized" vs "quantified" phrasing I mentioned above still doesn't sit well with me. Perhaps we could discuss it if you disagree?

**Comment by Cavenfish** [comment]
@shivupa My apologies, I thought I changed it already. I completely agree with you, it should be `quantified` not `quantized`.

**Comment by shivupa** [comment]
no worries!
